bash fix now with inputs for tests

diff --git a/.github/workflows/quality-gate-challenge.yml b/.github/workflows/quality-gate-challenge.yml
--- a/.github/workflows/quality-gate-challenge.yml
+++ b/.github/workflows/quality-gate-challenge.yml
@@ -1,13 +1,20 @@
 name: CI Quality Gate
 on:
-  workflow_dispatch
+  workflow_dispatch:
+    inputs:
+      porcetagem:
+        type: string
+        required: true
+      vulnerabilidades:
+        type: string
+        required: true
 jobs:
   tests:
     runs-on: ubuntu-latest
     steps:
       - name: Cobertura
         id: coverage
-        run: echo "porcentagem=87" >> $GITHUB_OUTPUT
+        run: echo "porcentagem=${{inputs.porcetagem}}" >> $GITHUB_OUTPUT
     outputs:
       cobertura: ${{ steps.coverage.outputs.porcentagem }}
 
@@ -16,7 +23,7 @@ jobs:
     steps:
       - name: Segurança
         id: security
-        run: echo "vulnerabilidades=0" >> $GITHUB_OUTPUT
+        run: echo "vulnerabilidades=${{inputs.vulnerabilidades}}" >> $GITHUB_OUTPUT
     outputs:
       vulnerabilidades: ${{steps.security.outputs.vulnerabilidades}}
   quality-gate:
@@ -29,10 +36,12 @@ jobs:
           VULNERABILITIES: ${{ needs.security.outputs.vulnerabilidades }}
           MINIMUM_COVERAGE: ${{ vars.COBERTURA_MINIMA }}
         run: |
-          echo "$MINIMUM_COVERAGE"
+          echo "Coberetura mínima: $MINIMUM_COVERAGE%"
           echo "Cobertura obtida: $COVERAGE%"
           echo "Vulnerabilidades: $VULNERABILITIES"
-          if (( $TESTE_COBERTURA > 80  || $VULNERABILITIES < 0 )); then
+          if (( COVERAGE >= MINIMUM_COVERAGE && $VULNERABILITIES == 0 )); then
             echo "::success::Build aprovado!"
-            exit 1
+            exit 0
           fi
+          echo "::error::Build reprovado!"
+          exit 1
